name: CICD

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.Docker_PASSWORD }}
      - name: Build and push
        uses: ./
        with:
          context: ./
          file: ./Dockerfile
      - name: Publish image to docker hub
        run: docker push practice/node-app:latest
        
  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull image from docker hub
        run: docker pull practice/node-app:latest
      - name: Delete old container
        run: docker rm -f node-app-container
      - name: Run docker container
        run: docker run -d -p 8080:8080 --name node-app-container practice/node-app